### ISSUE TITLE
Big Bug When Want to chat

### ISSUE THREAD

**Issue by andhra21231** [pelajarsocial/pkchat-client#6]
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.client.chatwindow.CellRenderer$1.updateItem(CellRenderer.java:34)
        at com.client.chatwindow.CellRenderer$1.updateItem(CellRenderer.java:17)
        at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
        at javafx.scene.control.ListCell.indexChanged(ListCell.java:330)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
        at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
        at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1879)
        at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2528)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1189)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:399)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:398)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:425)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:561)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:541)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:534)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:340)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.client.chatwindow.ChatController.lambda$newUserNotification$6(ChatController.java:193)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
92721 [Thread-4] INFO com.client.chatwindow.ChatController - setUserList() method Enter
92728 [Thread-4] INFO com.client.chatwindow.ChatController - setUserList() method Exit
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.client.chatwindow.CellRenderer$1.updateItem(CellRenderer.java:34)
        at com.client.chatwindow.CellRenderer$1.updateItem(CellRenderer.java:17)
        at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
        at javafx.scene.control.ListCell.access$300(ListCell.java:72)
        at javafx.scene.control.ListCell$2.changed(ListCell.java:185)
        at javafx.scene.control.ListCell$2.changed(ListCell.java:175)
        at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
        at javafx.scene.control.ListView.setItems(ListView.java:390)
        at com.client.chatwindow.ChatController.lambda$setUserList$5(ChatController.java:183)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)

**Comment by andhra21231** [comment]
Fixed
